// Code generated by MockGen. DO NOT EDIT.
// Source: custom_wrappers.go

// Package mock_errors is a generated GoMock package.
package mock_errors

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCustomWrapper is a mock of CustomWrapper interface.
type MockCustomWrapper struct {
	ctrl     *gomock.Controller
	recorder *MockCustomWrapperMockRecorder
}

// MockCustomWrapperMockRecorder is the mock recorder for MockCustomWrapper.
type MockCustomWrapperMockRecorder struct {
	mock *MockCustomWrapper
}

// NewMockCustomWrapper creates a new mock instance.
func NewMockCustomWrapper(ctrl *gomock.Controller) *MockCustomWrapper {
	mock := &MockCustomWrapper{ctrl: ctrl}
	mock.recorder = &MockCustomWrapperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomWrapper) EXPECT() *MockCustomWrapperMockRecorder {
	return m.recorder
}

// Wrap mocks base method.
func (m *MockCustomWrapper) Wrap(err error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Wrap", err)
	ret0, _ := ret[0].(error)
	return ret0
}

// Wrap indicates an expected call of Wrap.
func (mr *MockCustomWrapperMockRecorder) Wrap(err interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wrap", reflect.TypeOf((*MockCustomWrapper)(nil).Wrap), err)
}
