// Code generated by MockGen. DO NOT EDIT.
// Source: runtime_wrappers.go

// Package mock_errors is a generated GoMock package.
package mock_errors

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockWrapper is a mock of Wrapper interface.
type MockWrapper struct {
	ctrl     *gomock.Controller
	recorder *MockWrapperMockRecorder
}

// MockWrapperMockRecorder is the mock recorder for MockWrapper.
type MockWrapperMockRecorder struct {
	mock *MockWrapper
}

// NewMockWrapper creates a new mock instance.
func NewMockWrapper(ctrl *gomock.Controller) *MockWrapper {
	mock := &MockWrapper{ctrl: ctrl}
	mock.recorder = &MockWrapperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWrapper) EXPECT() *MockWrapperMockRecorder {
	return m.recorder
}

// Wrap mocks base method.
func (m *MockWrapper) Wrap(err error, attrs ...any) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{err}
	for _, a := range attrs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Wrap", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Wrap indicates an expected call of Wrap.
func (mr *MockWrapperMockRecorder) Wrap(err interface{}, attrs ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{err}, attrs...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wrap", reflect.TypeOf((*MockWrapper)(nil).Wrap), varargs...)
}
