// Code generated by MockGen. DO NOT EDIT.
// Source: hint.go

// Package mock_hint is a generated GoMock package.
package mock_hint

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	kind "github.com/mondegor/go-sysmess/errors/kind"
)

// MockHint is a mock of Hint interface.
type MockHint struct {
	ctrl     *gomock.Controller
	recorder *MockHintMockRecorder
}

// MockHintMockRecorder is the mock recorder for MockHint.
type MockHintMockRecorder struct {
	mock *MockHint
}

// NewMockHint creates a new mock instance.
func NewMockHint(ctrl *gomock.Controller) *MockHint {
	mock := &MockHint{ctrl: ctrl}
	mock.recorder = &MockHintMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHint) EXPECT() *MockHintMockRecorder {
	return m.recorder
}

// ErrorID mocks base method.
func (m *MockHint) ErrorID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ErrorID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ErrorID indicates an expected call of ErrorID.
func (mr *MockHintMockRecorder) ErrorID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ErrorID", reflect.TypeOf((*MockHint)(nil).ErrorID))
}

// ErrorKind mocks base method.
func (m *MockHint) ErrorKind() kind.Enum {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ErrorKind")
	ret0, _ := ret[0].(kind.Enum)
	return ret0
}

// ErrorKind indicates an expected call of ErrorKind.
func (mr *MockHintMockRecorder) ErrorKind() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ErrorKind", reflect.TypeOf((*MockHint)(nil).ErrorKind))
}

// StackTraceIterator mocks base method.
func (m *MockHint) StackTraceIterator() func() (int, string, string, int) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StackTraceIterator")
	ret0, _ := ret[0].(func() (int, string, string, int))
	return ret0
}

// StackTraceIterator indicates an expected call of StackTraceIterator.
func (mr *MockHintMockRecorder) StackTraceIterator() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StackTraceIterator", reflect.TypeOf((*MockHint)(nil).StackTraceIterator))
}

// MockstackTrace is a mock of stackTrace interface.
type MockstackTrace struct {
	ctrl     *gomock.Controller
	recorder *MockstackTraceMockRecorder
}

// MockstackTraceMockRecorder is the mock recorder for MockstackTrace.
type MockstackTraceMockRecorder struct {
	mock *MockstackTrace
}

// NewMockstackTrace creates a new mock instance.
func NewMockstackTrace(ctrl *gomock.Controller) *MockstackTrace {
	mock := &MockstackTrace{ctrl: ctrl}
	mock.recorder = &MockstackTraceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockstackTrace) EXPECT() *MockstackTraceMockRecorder {
	return m.recorder
}

// Iterator mocks base method.
func (m *MockstackTrace) Iterator() func() (int, string, string, int) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Iterator")
	ret0, _ := ret[0].(func() (int, string, string, int))
	return ret0
}

// Iterator indicates an expected call of Iterator.
func (mr *MockstackTraceMockRecorder) Iterator() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Iterator", reflect.TypeOf((*MockstackTrace)(nil).Iterator))
}
