@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

' mrerr
!include components/c4/mrerr/instant_error.iuml
!include components/c4/mrerr/custom_error.iuml
!include components/c4/mrerr/id_generator.iuml
!include components/c4/mrerr/proto_error.iuml
!include components/c4/mrerr/stack_caller.iuml

' errcore
!include components/c4/errcore/error_handler.iuml
!include components/c4/errcore/init_error_engine.iuml
!include components/c4/errcore/logger.iuml
!include components/c4/errcore/sentry_handler.iuml

' app
!include components/c4/app/app_component.iuml
!include components/c4/app/app_controller.iuml

' ext
!include components/c4/ext/sentry.iuml
!include components/c4/ext/user.iuml

' containers
!include components/c4/app.iuml
!include components/c4/mrerr.iuml
!include components/c4/err_core.iuml

@enduml