// Code generated by MockGen. DO NOT EDIT.
// Source: delayed_options.go

// Package mock_runtime is a generated GoMock package.
package mock_runtime

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	kind "github.com/mondegor/go-sysmess/errors/kind"
	runtime "github.com/mondegor/go-sysmess/errors/runtime"
)

// MockOptionsHandler is a mock of OptionsHandler interface.
type MockOptionsHandler struct {
	ctrl     *gomock.Controller
	recorder *MockOptionsHandlerMockRecorder
}

// MockOptionsHandlerMockRecorder is the mock recorder for MockOptionsHandler.
type MockOptionsHandlerMockRecorder struct {
	mock *MockOptionsHandler
}

// NewMockOptionsHandler creates a new mock instance.
func NewMockOptionsHandler(ctrl *gomock.Controller) *MockOptionsHandler {
	mock := &MockOptionsHandler{ctrl: ctrl}
	mock.recorder = &MockOptionsHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOptionsHandler) EXPECT() *MockOptionsHandlerMockRecorder {
	return m.recorder
}

// Options mocks base method.
func (m *MockOptionsHandler) Options(kindErr kind.Enum, message string) []runtime.Option {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Options", kindErr, message)
	ret0, _ := ret[0].([]runtime.Option)
	return ret0
}

// Options indicates an expected call of Options.
func (mr *MockOptionsHandlerMockRecorder) Options(kindErr, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Options", reflect.TypeOf((*MockOptionsHandler)(nil).Options), kindErr, message)
}
