// Code generated by MockGen. DO NOT EDIT.
// Source: runtime_error.go

// Package mock_runtime is a generated GoMock package.
package mock_runtime

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	kind "github.com/mondegor/go-sysmess/errors/kind"
)

// MockProtoError is a mock of ProtoError interface.
type MockProtoError struct {
	ctrl     *gomock.Controller
	recorder *MockProtoErrorMockRecorder
}

// MockProtoErrorMockRecorder is the mock recorder for MockProtoError.
type MockProtoErrorMockRecorder struct {
	mock *MockProtoError
}

// NewMockProtoError creates a new mock instance.
func NewMockProtoError(ctrl *gomock.Controller) *MockProtoError {
	mock := &MockProtoError{ctrl: ctrl}
	mock.recorder = &MockProtoErrorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProtoError) EXPECT() *MockProtoErrorMockRecorder {
	return m.recorder
}

// Error mocks base method.
func (m *MockProtoError) Error() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Error")
	ret0, _ := ret[0].(string)
	return ret0
}

// Error indicates an expected call of Error.
func (mr *MockProtoErrorMockRecorder) Error() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockProtoError)(nil).Error))
}

// Kind mocks base method.
func (m *MockProtoError) Kind() kind.Enum {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Kind")
	ret0, _ := ret[0].(kind.Enum)
	return ret0
}

// Kind indicates an expected call of Kind.
func (mr *MockProtoErrorMockRecorder) Kind() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Kind", reflect.TypeOf((*MockProtoError)(nil).Kind))
}

// New mocks base method.
func (m *MockProtoError) New(attrs ...any) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range attrs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "New", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// New indicates an expected call of New.
func (mr *MockProtoErrorMockRecorder) New(attrs ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockProtoError)(nil).New), attrs...)
}

// WithDetails mocks base method.
func (m *MockProtoError) WithDetails(details string, attrs ...any) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{details}
	for _, a := range attrs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WithDetails", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithDetails indicates an expected call of WithDetails.
func (mr *MockProtoErrorMockRecorder) WithDetails(details interface{}, attrs ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{details}, attrs...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithDetails", reflect.TypeOf((*MockProtoError)(nil).WithDetails), varargs...)
}

// WithError mocks base method.
func (m *MockProtoError) WithError(err error, details string, attrs ...any) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{err, details}
	for _, a := range attrs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WithError", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithError indicates an expected call of WithError.
func (mr *MockProtoErrorMockRecorder) WithError(err, details interface{}, attrs ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{err, details}, attrs...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithError", reflect.TypeOf((*MockProtoError)(nil).WithError), varargs...)
}

// Wrap mocks base method.
func (m *MockProtoError) Wrap(err error, attrs ...any) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{err}
	for _, a := range attrs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Wrap", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Wrap indicates an expected call of Wrap.
func (mr *MockProtoErrorMockRecorder) Wrap(err interface{}, attrs ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{err}, attrs...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wrap", reflect.TypeOf((*MockProtoError)(nil).Wrap), varargs...)
}
