// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package fruitcat

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func NewCatalog() catalog.Catalog {
	dict := map[string]catalog.Dictionary{
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
		"ru_RU": &dictionary{index: ru_RUIndex, data: ru_RUData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	return cat
}

var messageKeyToIndex = map[string]int{
	"id7391":  0,
	"id97104": 1,
}

var en_USIndex = []uint32{ // 3 elements
	0x00000000, 0x0000002c, 0x00000074,
} // Size: 36 bytes

const en_USData string = "" + // Size: 116 bytes
	"\x027391|Pineapple|A perennial herbaceous plant\x0297104|Plum|A deciduou" +
	"s tree that includes many varieties of fruit trees"

var ru_RUIndex = []uint32{ // 3 elements
	0x00000000, 0x00000051, 0x00000107,
} // Size: 36 bytes

const ru_RUData string = "" + // Size: 263 bytes
	"\x027391|Ананас|Многолетнее травянистое растение\x0297104|Слива|Листопад" +
	"ное дерево, которое включает в себя множество разновидностей фруктовых " +
	"деревьев"

	// Total table size 451 bytes (0KiB); checksum: FC05C3E5
