// Code generated by MockGen. DO NOT EDIT.
// Source: caller.go

// Package mock_stacktrace is a generated GoMock package.
package mock_stacktrace

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	stacktrace "github.com/mondegor/go-sysmess/errors/runtime/stacktrace"
)

// MockCaller is a mock of Caller interface.
type MockCaller struct {
	ctrl     *gomock.Controller
	recorder *MockCallerMockRecorder
}

// MockCallerMockRecorder is the mock recorder for MockCaller.
type MockCallerMockRecorder struct {
	mock *MockCaller
}

// NewMockCaller creates a new mock instance.
func NewMockCaller(ctrl *gomock.Controller) *MockCaller {
	mock := &MockCaller{ctrl: ctrl}
	mock.recorder = &MockCallerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCaller) EXPECT() *MockCallerMockRecorder {
	return m.recorder
}

// Call mocks base method.
func (m *MockCaller) Call() stacktrace.StackTrace {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Call")
	ret0, _ := ret[0].(stacktrace.StackTrace)
	return ret0
}

// Call indicates an expected call of Call.
func (mr *MockCallerMockRecorder) Call() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Call", reflect.TypeOf((*MockCaller)(nil).Call))
}

// MockStackTrace is a mock of StackTrace interface.
type MockStackTrace struct {
	ctrl     *gomock.Controller
	recorder *MockStackTraceMockRecorder
}

// MockStackTraceMockRecorder is the mock recorder for MockStackTrace.
type MockStackTraceMockRecorder struct {
	mock *MockStackTrace
}

// NewMockStackTrace creates a new mock instance.
func NewMockStackTrace(ctrl *gomock.Controller) *MockStackTrace {
	mock := &MockStackTrace{ctrl: ctrl}
	mock.recorder = &MockStackTraceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStackTrace) EXPECT() *MockStackTraceMockRecorder {
	return m.recorder
}

// Iterator mocks base method.
func (m *MockStackTrace) Iterator() func() (int, string, string, int) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Iterator")
	ret0, _ := ret[0].(func() (int, string, string, int))
	return ret0
}

// Iterator indicates an expected call of Iterator.
func (mr *MockStackTraceMockRecorder) Iterator() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Iterator", reflect.TypeOf((*MockStackTrace)(nil).Iterator))
}
