// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mondegor/go-core/mrtrace (interfaces: ContextManager)
//
// Generated by this command:
//
//	mockgen -destination=./mock/mrtrace.go -package=mock github.com/mondegor/go-core/mrtrace ContextManager
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockContextManager is a mock of ContextManager interface.
type MockContextManager struct {
	ctrl     *gomock.Controller
	recorder *MockContextManagerMockRecorder
	isgomock struct{}
}

// MockContextManagerMockRecorder is the mock recorder for MockContextManager.
type MockContextManagerMockRecorder struct {
	mock *MockContextManager
}

// NewMockContextManager creates a new mock instance.
func NewMockContextManager(ctrl *gomock.Controller) *MockContextManager {
	mock := &MockContextManager{ctrl: ctrl}
	mock.recorder = &MockContextManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContextManager) EXPECT() *MockContextManagerMockRecorder {
	return m.recorder
}

// ExtractCorrelationID mocks base method.
func (m *MockContextManager) ExtractCorrelationID(ctx context.Context) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractCorrelationID", ctx)
	ret0, _ := ret[0].(string)
	return ret0
}

// ExtractCorrelationID indicates an expected call of ExtractCorrelationID.
func (mr *MockContextManagerMockRecorder) ExtractCorrelationID(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractCorrelationID", reflect.TypeOf((*MockContextManager)(nil).ExtractCorrelationID), ctx)
}

// ExtractKeysValues mocks base method.
func (m *MockContextManager) ExtractKeysValues(ctx context.Context) []any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractKeysValues", ctx)
	ret0, _ := ret[0].([]any)
	return ret0
}

// ExtractKeysValues indicates an expected call of ExtractKeysValues.
func (mr *MockContextManagerMockRecorder) ExtractKeysValues(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractKeysValues", reflect.TypeOf((*MockContextManager)(nil).ExtractKeysValues), ctx)
}

// ProcessID mocks base method.
func (m *MockContextManager) ProcessID(ctx context.Context, key string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessID", ctx, key)
	ret0, _ := ret[0].(string)
	return ret0
}

// ProcessID indicates an expected call of ProcessID.
func (mr *MockContextManagerMockRecorder) ProcessID(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessID", reflect.TypeOf((*MockContextManager)(nil).ProcessID), ctx, key)
}

// WithGeneratedProcessID mocks base method.
func (m *MockContextManager) WithGeneratedProcessID(ctx context.Context, key string) context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithGeneratedProcessID", ctx, key)
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// WithGeneratedProcessID indicates an expected call of WithGeneratedProcessID.
func (mr *MockContextManagerMockRecorder) WithGeneratedProcessID(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithGeneratedProcessID", reflect.TypeOf((*MockContextManager)(nil).WithGeneratedProcessID), ctx, key)
}

// WithProcessID mocks base method.
func (m *MockContextManager) WithProcessID(ctx context.Context, key, value string) context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithProcessID", ctx, key, value)
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// WithProcessID indicates an expected call of WithProcessID.
func (mr *MockContextManagerMockRecorder) WithProcessID(ctx, key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithProcessID", reflect.TypeOf((*MockContextManager)(nil).WithProcessID), ctx, key, value)
}
