// Code generated by MockGen. DO NOT EDIT.
// Source: user_error.go

// Package mock_user is a generated GoMock package.
package mock_user

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockProtoError is a mock of ProtoError interface.
type MockProtoError struct {
	ctrl     *gomock.Controller
	recorder *MockProtoErrorMockRecorder
}

// MockProtoErrorMockRecorder is the mock recorder for MockProtoError.
type MockProtoErrorMockRecorder struct {
	mock *MockProtoError
}

// NewMockProtoError creates a new mock instance.
func NewMockProtoError(ctrl *gomock.Controller) *MockProtoError {
	mock := &MockProtoError{ctrl: ctrl}
	mock.recorder = &MockProtoErrorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProtoError) EXPECT() *MockProtoErrorMockRecorder {
	return m.recorder
}

// Code mocks base method.
func (m *MockProtoError) Code() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Code")
	ret0, _ := ret[0].(string)
	return ret0
}

// Code indicates an expected call of Code.
func (mr *MockProtoErrorMockRecorder) Code() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Code", reflect.TypeOf((*MockProtoError)(nil).Code))
}

// Error mocks base method.
func (m *MockProtoError) Error() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Error")
	ret0, _ := ret[0].(string)
	return ret0
}

// Error indicates an expected call of Error.
func (mr *MockProtoErrorMockRecorder) Error() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockProtoError)(nil).Error))
}

// New mocks base method.
func (m *MockProtoError) New(args ...any) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "New", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// New indicates an expected call of New.
func (mr *MockProtoErrorMockRecorder) New(args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockProtoError)(nil).New), args...)
}

// Wrap mocks base method.
func (m *MockProtoError) Wrap(err error, args ...any) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{err}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Wrap", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Wrap indicates an expected call of Wrap.
func (mr *MockProtoErrorMockRecorder) Wrap(err interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{err}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wrap", reflect.TypeOf((*MockProtoError)(nil).Wrap), varargs...)
}
