// Code generated by MockGen. DO NOT EDIT.
// Source: custom_error.go

// Package mock_custom is a generated GoMock package.
package mock_custom

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockError is a mock of Error interface.
type MockError struct {
	ctrl     *gomock.Controller
	recorder *MockErrorMockRecorder
}

// MockErrorMockRecorder is the mock recorder for MockError.
type MockErrorMockRecorder struct {
	mock *MockError
}

// NewMockError creates a new mock instance.
func NewMockError(ctrl *gomock.Controller) *MockError {
	mock := &MockError{ctrl: ctrl}
	mock.recorder = &MockErrorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockError) EXPECT() *MockErrorMockRecorder {
	return m.recorder
}

// CustomCode mocks base method.
func (m *MockError) CustomCode() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CustomCode")
	ret0, _ := ret[0].(string)
	return ret0
}

// CustomCode indicates an expected call of CustomCode.
func (mr *MockErrorMockRecorder) CustomCode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CustomCode", reflect.TypeOf((*MockError)(nil).CustomCode))
}

// Error mocks base method.
func (m *MockError) Error() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Error")
	ret0, _ := ret[0].(string)
	return ret0
}

// Error indicates an expected call of Error.
func (mr *MockErrorMockRecorder) Error() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockError)(nil).Error))
}

// IsKindUser mocks base method.
func (m *MockError) IsKindUser() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsKindUser")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsKindUser indicates an expected call of IsKindUser.
func (mr *MockErrorMockRecorder) IsKindUser() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsKindUser", reflect.TypeOf((*MockError)(nil).IsKindUser))
}

// Unwrap mocks base method.
func (m *MockError) Unwrap() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unwrap")
	ret0, _ := ret[0].(error)
	return ret0
}

// Unwrap indicates an expected call of Unwrap.
func (mr *MockErrorMockRecorder) Unwrap() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unwrap", reflect.TypeOf((*MockError)(nil).Unwrap))
}
