// Code generated by MockGen. DO NOT EDIT.
// Source: item_batch_player.go
//
// Generated by this command:
//
//	mockgen -source=item_batch_player.go -destination=./mock/helper.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// Mockhandler is a mock of handler interface.
type Mockhandler struct {
	ctrl     *gomock.Controller
	recorder *MockhandlerMockRecorder
	isgomock struct{}
}

// MockhandlerMockRecorder is the mock recorder for Mockhandler.
type MockhandlerMockRecorder struct {
	mock *Mockhandler
}

// NewMockhandler creates a new mock instance.
func NewMockhandler(ctrl *gomock.Controller) *Mockhandler {
	mock := &Mockhandler{ctrl: ctrl}
	mock.recorder = &MockhandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockhandler) EXPECT() *MockhandlerMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *Mockhandler) Execute(ctx context.Context, limit int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, limit)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockhandlerMockRecorder) Execute(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*Mockhandler)(nil).Execute), ctx, limit)
}

// MockeventEmitter is a mock of eventEmitter interface.
type MockeventEmitter struct {
	ctrl     *gomock.Controller
	recorder *MockeventEmitterMockRecorder
	isgomock struct{}
}

// MockeventEmitterMockRecorder is the mock recorder for MockeventEmitter.
type MockeventEmitterMockRecorder struct {
	mock *MockeventEmitter
}

// NewMockeventEmitter creates a new mock instance.
func NewMockeventEmitter(ctrl *gomock.Controller) *MockeventEmitter {
	mock := &MockeventEmitter{ctrl: ctrl}
	mock.recorder = &MockeventEmitterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockeventEmitter) EXPECT() *MockeventEmitterMockRecorder {
	return m.recorder
}

// Emit mocks base method.
func (m *MockeventEmitter) Emit(ctx context.Context, eventName string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, eventName}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Emit", varargs...)
}

// Emit indicates an expected call of Emit.
func (mr *MockeventEmitterMockRecorder) Emit(ctx, eventName any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, eventName}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Emit", reflect.TypeOf((*MockeventEmitter)(nil).Emit), varargs...)
}
