// Code generated by MockGen. DO NOT EDIT.
// Source: trace.go

// Package mock_mrtrace is a generated GoMock package.
package mock_mrtrace

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTracer is a mock of Tracer interface.
type MockTracer struct {
	ctrl     *gomock.Controller
	recorder *MockTracerMockRecorder
}

// MockTracerMockRecorder is the mock recorder for MockTracer.
type MockTracerMockRecorder struct {
	mock *MockTracer
}

// NewMockTracer creates a new mock instance.
func NewMockTracer(ctrl *gomock.Controller) *MockTracer {
	mock := &MockTracer{ctrl: ctrl}
	mock.recorder = &MockTracerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTracer) EXPECT() *MockTracerMockRecorder {
	return m.recorder
}

// Enabled mocks base method.
func (m *MockTracer) Enabled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Enabled indicates an expected call of Enabled.
func (mr *MockTracerMockRecorder) Enabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enabled", reflect.TypeOf((*MockTracer)(nil).Enabled))
}

// Trace mocks base method.
func (m *MockTracer) Trace(ctx context.Context, args ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Trace", varargs...)
}

// Trace indicates an expected call of Trace.
func (mr *MockTracerMockRecorder) Trace(ctx interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trace", reflect.TypeOf((*MockTracer)(nil).Trace), varargs...)
}

// MockContextManager is a mock of ContextManager interface.
type MockContextManager struct {
	ctrl     *gomock.Controller
	recorder *MockContextManagerMockRecorder
}

// MockContextManagerMockRecorder is the mock recorder for MockContextManager.
type MockContextManagerMockRecorder struct {
	mock *MockContextManager
}

// NewMockContextManager creates a new mock instance.
func NewMockContextManager(ctrl *gomock.Controller) *MockContextManager {
	mock := &MockContextManager{ctrl: ctrl}
	mock.recorder = &MockContextManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContextManager) EXPECT() *MockContextManagerMockRecorder {
	return m.recorder
}

// ExtractCorrelationID mocks base method.
func (m *MockContextManager) ExtractCorrelationID(ctx context.Context) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractCorrelationID", ctx)
	ret0, _ := ret[0].(string)
	return ret0
}

// ExtractCorrelationID indicates an expected call of ExtractCorrelationID.
func (mr *MockContextManagerMockRecorder) ExtractCorrelationID(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractCorrelationID", reflect.TypeOf((*MockContextManager)(nil).ExtractCorrelationID), ctx)
}

// ExtractKeysValues mocks base method.
func (m *MockContextManager) ExtractKeysValues(ctx context.Context) []any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractKeysValues", ctx)
	ret0, _ := ret[0].([]any)
	return ret0
}

// ExtractKeysValues indicates an expected call of ExtractKeysValues.
func (mr *MockContextManagerMockRecorder) ExtractKeysValues(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractKeysValues", reflect.TypeOf((*MockContextManager)(nil).ExtractKeysValues), ctx)
}

// ID mocks base method.
func (m *MockContextManager) ID(ctx context.Context) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID", ctx)
	ret0, _ := ret[0].(string)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockContextManagerMockRecorder) ID(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockContextManager)(nil).ID), ctx)
}

// NewContextWithIDs mocks base method.
func (m *MockContextManager) NewContextWithIDs(originalCtx context.Context) context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewContextWithIDs", originalCtx)
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// NewContextWithIDs indicates an expected call of NewContextWithIDs.
func (mr *MockContextManagerMockRecorder) NewContextWithIDs(originalCtx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewContextWithIDs", reflect.TypeOf((*MockContextManager)(nil).NewContextWithIDs), originalCtx)
}

// WithGeneratedID mocks base method.
func (m *MockContextManager) WithGeneratedID(ctx context.Context) context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithGeneratedID", ctx)
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// WithGeneratedID indicates an expected call of WithGeneratedID.
func (mr *MockContextManagerMockRecorder) WithGeneratedID(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithGeneratedID", reflect.TypeOf((*MockContextManager)(nil).WithGeneratedID), ctx)
}

// WithID mocks base method.
func (m *MockContextManager) WithID(ctx context.Context, id string) context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithID", ctx, id)
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// WithID indicates an expected call of WithID.
func (mr *MockContextManagerMockRecorder) WithID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithID", reflect.TypeOf((*MockContextManager)(nil).WithID), ctx, id)
}
