// Code generated by MockGen. DO NOT EDIT.
// Source: custom_wrapper.go

// Package mock_wrap is a generated GoMock package.
package mock_wrap

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCustomErrorWrapper is a mock of CustomErrorWrapper interface.
type MockCustomErrorWrapper struct {
	ctrl     *gomock.Controller
	recorder *MockCustomErrorWrapperMockRecorder
}

// MockCustomErrorWrapperMockRecorder is the mock recorder for MockCustomErrorWrapper.
type MockCustomErrorWrapperMockRecorder struct {
	mock *MockCustomErrorWrapper
}

// NewMockCustomErrorWrapper creates a new mock instance.
func NewMockCustomErrorWrapper(ctrl *gomock.Controller) *MockCustomErrorWrapper {
	mock := &MockCustomErrorWrapper{ctrl: ctrl}
	mock.recorder = &MockCustomErrorWrapperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomErrorWrapper) EXPECT() *MockCustomErrorWrapperMockRecorder {
	return m.recorder
}

// Wrap mocks base method.
func (m *MockCustomErrorWrapper) Wrap(err error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Wrap", err)
	ret0, _ := ret[0].(error)
	return ret0
}

// Wrap indicates an expected call of Wrap.
func (mr *MockCustomErrorWrapperMockRecorder) Wrap(err interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wrap", reflect.TypeOf((*MockCustomErrorWrapper)(nil).Wrap), err)
}
