// Code generated by MockGen. DO NOT EDIT.
// Source: error_wrapper.go

// Package mock_wrap is a generated GoMock package.
package mock_wrap

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockErrorWrapper is a mock of ErrorWrapper interface.
type MockErrorWrapper struct {
	ctrl     *gomock.Controller
	recorder *MockErrorWrapperMockRecorder
}

// MockErrorWrapperMockRecorder is the mock recorder for MockErrorWrapper.
type MockErrorWrapperMockRecorder struct {
	mock *MockErrorWrapper
}

// NewMockErrorWrapper creates a new mock instance.
func NewMockErrorWrapper(ctrl *gomock.Controller) *MockErrorWrapper {
	mock := &MockErrorWrapper{ctrl: ctrl}
	mock.recorder = &MockErrorWrapperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockErrorWrapper) EXPECT() *MockErrorWrapperMockRecorder {
	return m.recorder
}

// Wrap mocks base method.
func (m *MockErrorWrapper) Wrap(err error, attrs ...any) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{err}
	for _, a := range attrs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Wrap", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Wrap indicates an expected call of Wrap.
func (mr *MockErrorWrapperMockRecorder) Wrap(err interface{}, attrs ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{err}, attrs...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wrap", reflect.TypeOf((*MockErrorWrapper)(nil).Wrap), varargs...)
}
