// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package msgcat

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func NewCatalog() catalog.Catalog {
	dict := map[string]catalog.Dictionary{
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
		"ru_RU": &dictionary{index: ru_RUIndex, data: ru_RUData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	return cat
}

var messageKeyToIndex = map[string]int{
	"Message example":                                 0,
	"Message example with param %s":                   1,
	"Message example with two params %[1]s and %[2]s": 2,
	"Total %d message(s)":                             3,
}

var en_USIndex = []uint32{ // 5 elements
	0x00000000, 0x00000010, 0x00000031, 0x00000061,
	0x000000a5,
} // Size: 44 bytes

const en_USData string = "" + // Size: 165 bytes
	"\x02Message example\x02Message example with param %[1]s\x02Message examp" +
	"le with two params %[1]s and %[2]s\x14\x01\x81\x01\x00=\x00\x16\x02There" +
	" are no messages=\x01\x0c\x02One message\x00\x15\x02Total %[1]d messages"

var ru_RUIndex = []uint32{ // 5 elements
	0x00000000, 0x00000020, 0x0000005e, 0x000000d8,
	0x000001a6,
} // Size: 44 bytes

const ru_RUData string = "" + // Size: 422 bytes
	"\x02Пример сообщения\x02Пример сообщения с параметром %[1]s\x02Пример со" +
	"общения с двумя параметрами поменянными местами %[2]s и %[1]s\x14\x01" +
	"\x81\x01\x00=\x00*\x02Сообщения отсутствуют=\x01'\x02Всего одно сообщени" +
	"е\x04$\x02Всего %[1]d сообщения\x02$\x02Всего %[1]d сообщение\x00$\x02В" +
	"сего %[1]d сообщений"

	// Total table size 675 bytes (0KiB); checksum: C9655F29
